Feature/avalentinagd/registerview
luigiRP/Post-it pull request #12
Opened 2020-08-28 07:58 UTC by avalentinagd

2020-08-28 13:21 UTC, luigiRP approved these changes

2020-09-16 13:28 UTC, JimenaEB requested changes

2020-09-16 13:28 UTC, JimenaEB commented on src/js/component/footer.js
> +//<p>
Borra los comentarios por fa

2020-09-16 13:28 UTC, JimenaEB commented on src/js/views/login.js
> +		<br />
Los br cambialos por css

2020-09-23 18:51 UTC, merged